[workspace]
name = "100DaysofCode-Rust"
authors = "Vimal A R <arvimal81@gmail.com>"

members = [
  "Day-001/*/",
  "Day-002/*/",
  "Day-003/*/",
  "Day-004/*/",
  "Day-005/*/",
  "Day-006/*/",
  "Day-007/*/",
  "Day-008/*/",
]
